In [1]:
import pandas as pd
df=pd.read_csv("used_cars_messy.csv")
df

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,2581,Renault Duster,Renault,Duster,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,224,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,1803,Honda City,Honda,City,3,48959,Dealer,Petrol,Manual,NaN,1497.0,117.60,5.0,875000.0
3,2728,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.4,2179.0,NaN,8.0,925000.0
4,14160,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.0,2179.0,140.00,7.0,1175000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,6581,Maruti Ertiga,Maruti,Ertiga,7,127731,Dealer,Diesel,Manual,20.77,1248.0,88.80,7.0,665000.0
15657,17029,Volkswagen Vento,Volkswagen,Vento,11,59000,Dealer,Petrol,Manual,16.09,NaN,103.20,5.0,249000.0
15658,6839,Maruti Wagon R,Maruti,Wagon R,7,20000,Individual,Petrol,Manual,20.51,998.0,67.04,5.0,250000.0
15659,1104,Hyundai i20,Hyundai,i20,2,15000,Dealer,Petrol,Manual,18.6,1197.0,81.86,5.0,620000.0
15660,9295,Maruti Ciaz,Maruti,Ciaz,2,30000,Individual,Petrol,Automatic,20.28,1462.0,103.25,5.0,960000.0

In [2]:
df.isnull().sum() * 100 / len(df)

Unnamed: 0            0.000000
car_name              0.000000
brand                 0.000000
model                 0.000000
vehicle_age           0.000000
km_driven             0.000000
seller_type           0.000000
fuel_type             0.000000
transmission_type     0.000000
mileage               8.205095
engine               11.934104
max_power             5.101845
seats                 2.828683
selling_price         1.008876
dtype: float64

In [3]:
df.shape

(15661, 14)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15661 entries, 0 to 15660
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15661 non-null  int64
 1   car_name           15661 non-null  str
 2   brand              15661 non-null  str
 3   model              15661 non-null  str
 4   vehicle_age        15661 non-null  int64
 5   km_driven          15661 non-null  str
 6   seller_type        15661 non-null  str
 7   fuel_type          15661 non-null  str
 8   transmission_type  15661 non-null  str
 9   mileage            14376 non-null  str
 10  engine             13792 non-null  float64
 11  max_power          14862 non-null  float64
 12  seats              15218 non-null  float64
 13  selling_price      15503 non-null  float64
dtypes: float64(4), int64(2), str(8)
memory usage: 1.7 MB

In [5]:
df["selling_price"].isnull().sum()

np.int64(158)

In [6]:
df.dropna(subset="selling_price",inplace=True)
print(df["selling_price"].isnull().sum())

0

In [7]:
df["mileage"].unique()

<StringArray>
[     '19.87',      '33.54',          nan,       '15.4',       '16.0',
      '20.36',       '18.5',      '20.51',       '24.4',       '19.3',
 ...
  '11.5 kmpl', '18.69 kmpl', '23.01 kmpl',       '20.2', '25.32 kmpl',
 '19.59 kmpl', '18.12 kmpl', '28.09 kmpl',  '17.7 kmpl', '24.04 kmpl']
Length: 513, dtype: str

In [8]:
df["mileage"]=df["mileage"].str.strip().str.title()
df["mileage"].unique()

<StringArray>
[     '19.87',      '33.54',          nan,       '15.4',       '16.0',
      '20.36',       '18.5',      '20.51',       '24.4',       '19.3',
 ...
  '11.5 Kmpl', '18.69 Kmpl', '23.01 Kmpl',       '20.2', '25.32 Kmpl',
 '19.59 Kmpl', '18.12 Kmpl', '28.09 Kmpl',  '17.7 Kmpl', '24.04 Kmpl']
Length: 513, dtype: str

In [9]:
df["mileage"]=df["mileage"].astype(str).str.replace("Kmpl","")
df["mileage"]

0        19.87
1        33.54
2          NaN
3         15.4
4         16.0
         ...
15656    20.77
15657    16.09
15658    20.51
15659     18.6
15660    20.28
Name: mileage, Length: 15503, dtype: str

In [10]:
df["mileage"]=df["mileage"].astype(str).str.replace("Km/L","")
df["mileage"]

0        19.87
1        33.54
2          NaN
3         15.4
4         16.0
         ...
15656    20.77
15657    16.09
15658    20.51
15659     18.6
15660    20.28
Name: mileage, Length: 15503, dtype: str

In [11]:
df["mileage"]=pd.to_numeric(df["mileage"],errors="coerce")
df["mileage"].isnull().sum()

np.int64(1269)

In [12]:
df["mileage"]=df["mileage"].fillna(df["mileage"].mean())
df["mileage"].isnull().sum()

np.int64(0)

In [14]:
df["mileage"]=pd.to_numeric(df["mileage"],errors="coerce")
df["mileage"]

0        19.870000
1        33.540000
2        19.697821
3        15.400000
4        16.000000
           ...
15656    20.770000
15657    16.090000
15658    20.510000
15659    18.600000
15660    20.280000
Name: mileage, Length: 15503, dtype: float64

In [15]:
df["engine"].isnull().sum()

np.int64(1852)

In [19]:
df["engine"]=df["engine"].fillna(df["engine"].mean())
df["engine"].isnull().sum()

np.int64(0)

In [20]:
df.info()

<class 'pandas.DataFrame'>
Index: 15503 entries, 0 to 15660
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15503 non-null  int64
 1   car_name           15503 non-null  str
 2   brand              15503 non-null  str
 3   model              15503 non-null  str
 4   vehicle_age        15503 non-null  int64
 5   km_driven          15503 non-null  str
 6   seller_type        15503 non-null  str
 7   fuel_type          15503 non-null  str
 8   transmission_type  15503 non-null  str
 9   mileage            15503 non-null  float64
 10  engine             15503 non-null  float64
 11  max_power          14712 non-null  float64
 12  seats              15065 non-null  float64
 13  selling_price      15503 non-null  float64
dtypes: float64(5), int64(2), str(7)
memory usage: 1.8 MB

In [24]:
df["max_power"].isnull().sum()
df["max_power"]=df["max_power"].fillna(df["max_power"].median())
df["max_power"].isnull().sum()
df

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,2581,Renault Duster,Renault,Duster,7,67647,Dealer,Diesel,Manual,19.870000,1461.000000,83.80,5.0,575000.0
1,224,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.540000,998.000000,67.04,5.0,435000.0
2,1803,Honda City,Honda,City,3,48959,Dealer,Petrol,Manual,19.697821,1497.000000,117.60,5.0,875000.0
3,2728,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.400000,2179.000000,88.50,8.0,925000.0
4,14160,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.000000,2179.000000,140.00,7.0,1175000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,6581,Maruti Ertiga,Maruti,Ertiga,7,127731,Dealer,Diesel,Manual,20.770000,1248.000000,88.80,7.0,665000.0
15657,17029,Volkswagen Vento,Volkswagen,Vento,11,59000,Dealer,Petrol,Manual,16.090000,1480.390521,103.20,5.0,249000.0
15658,6839,Maruti Wagon R,Maruti,Wagon R,7,20000,Individual,Petrol,Manual,20.510000,998.000000,67.04,5.0,250000.0
15659,1104,Hyundai i20,Hyundai,i20,2,15000,Dealer,Petrol,Manual,18.600000,1197.000000,81.86,5.0,620000.0
15660,9295,Maruti Ciaz,Maruti,Ciaz,2,30000,Individual,Petrol,Automatic,20.280000,1462.000000,103.25,5.0,960000.0

In [30]:
df.drop(columns=["Unnamed: 0"], inplace=True)
df

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Renault Duster,Renault,Duster,7,67647,Dealer,Diesel,Manual,19.870000,1461.000000,83.80,5.0,575000.0
1,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.540000,998.000000,67.04,5.0,435000.0
2,Honda City,Honda,City,3,48959,Dealer,Petrol,Manual,19.697821,1497.000000,117.60,5.0,875000.0
3,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.400000,2179.000000,88.50,8.0,925000.0
4,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.000000,2179.000000,140.00,7.0,1175000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,Maruti Ertiga,Maruti,Ertiga,7,127731,Dealer,Diesel,Manual,20.770000,1248.000000,88.80,7.0,665000.0
15657,Volkswagen Vento,Volkswagen,Vento,11,59000,Dealer,Petrol,Manual,16.090000,1480.390521,103.20,5.0,249000.0
15658,Maruti Wagon R,Maruti,Wagon R,7,20000,Individual,Petrol,Manual,20.510000,998.000000,67.04,5.0,250000.0
15659,Hyundai i20,Hyundai,i20,2,15000,Dealer,Petrol,Manual,18.600000,1197.000000,81.86,5.0,620000.0
15660,Maruti Ciaz,Maruti,Ciaz,2,30000,Individual,Petrol,Automatic,20.280000,1462.000000,103.25,5.0,960000.0

In [32]:
typo={"Manual":0,"Automatic":1}
df["transmission_type"]=df["transmission_type"].replace(typo)
df["transmission_type"]

0        0
1        0
2        0
3        0
4        1
        ..
15656    0
15657    0
15658    0
15659    0
15660    1
Name: transmission_type, Length: 15503, dtype: int64

In [37]:
df["fuel_type"].unique()

<StringArray>
[  'Diesel',      'CNG',   'Petrol',  'Petrol ',   'DIESEL',  ' Petrol',
  'petrol ',   'PETROL',  ' Diesel',  'diesel ',      'LPG',   'petrol',
   'diesel', 'Electric']
Length: 14, dtype: str

In [39]:
map={ 'Diesel':'DIESEL',
     ' Diesel':'DIESEL',
      'DIESEL':'DIESEL',
'diesel':'DIESEL',
'diesel ':'DIESEL',
'Petrol':'PETROL',
'Petrol ':'PETROL',
' Petrol':'PETROL',
'petrol ':'PETROL',
'PETROL':'PETROL',
'petrol':'PETROL',
     'CNG':'CNG',
     'LPG':'LPG',
     'Electric':'ELECTRIC'}
df["fuel_type"]=df["fuel_type"].replace(map)
df["fuel_type"].unique()

<StringArray>
['DIESEL', 'CNG', 'PETROL', 'LPG', 'ELECTRIC']
Length: 5, dtype: str

In [41]:
fuel_dummies = pd.get_dummies(df["fuel_type"], drop_first=True)
df = pd.concat([df, fuel_dummies], axis=1)
df["fuel_type"]

0        DIESEL
1           CNG
2        PETROL
3        DIESEL
4        DIESEL
          ...
15656    DIESEL
15657    PETROL
15658    PETROL
15659    PETROL
15660    PETROL
Name: fuel_type, Length: 15503, dtype: str

In [42]:
df

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,...,Petrol,Petrol,diesel,diesel,petrol,petrol,DIESEL,ELECTRIC,LPG,PETROL
0,Renault Duster,Renault,Duster,7,67647,Dealer,DIESEL,0,19.870000,1461.000000,...,False,False,False,False,False,False,True,False,False,False
1,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,0,33.540000,998.000000,...,False,False,False,False,False,False,False,False,False,False
2,Honda City,Honda,City,3,48959,Dealer,PETROL,0,19.697821,1497.000000,...,True,False,False,False,False,False,False,False,False,True
3,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,DIESEL,0,15.400000,2179.000000,...,False,False,False,False,False,False,True,False,False,False
4,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,DIESEL,1,16.000000,2179.000000,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,Maruti Ertiga,Maruti,Ertiga,7,127731,Dealer,DIESEL,0,20.770000,1248.000000,...,False,False,False,False,False,False,True,False,False,False
15657,Volkswagen Vento,Volkswagen,Vento,11,59000,Dealer,PETROL,0,16.090000,1480.390521,...,True,False,False,False,False,False,False,False,False,True
15658,Maruti Wagon R,Maruti,Wagon R,7,20000,Individual,PETROL,0,20.510000,998.000000,...,True,False,False,False,False,False,False,False,False,True
15659,Hyundai i20,Hyundai,i20,2,15000,Dealer,PETROL,0,18.600000,1197.000000,...,True,False,False,False,False,False,False,False,False,True
15660,Maruti Ciaz,Maruti,Ciaz,2,30000,Individual,PETROL,1,20.280000,1462.000000,...,True,False,False,False,False,False,False,False,False,True

In [43]:
df.columns.tolist()

['car_name',
 'brand',
 'model',
 'vehicle_age',
 'km_driven',
 'seller_type',
 'fuel_type',
 'transmission_type',
 'mileage',
 'engine',
 'max_power',
 'seats',
 'selling_price',
 ' Petrol',
 'CNG',
 'DIESEL',
 'Diesel',
 'Electric',
 'LPG',
 'PETROL',
 'Petrol',
 'Petrol ',
 'diesel',
 'diesel ',
 'petrol',
 'petrol ',
 'DIESEL',
 'ELECTRIC',
 'LPG',
 'PETROL']

In [45]:
X = df.drop(columns=["selling_price"])
y = df["selling_price"]
X = X.select_dtypes(include=["number"])
X

,vehicle_age,transmission_type,mileage,engine,max_power,seats
0,7,0,19.870000,1461.000000,83.80,5.0
1,3,0,33.540000,998.000000,67.04,5.0
2,3,0,19.697821,1497.000000,117.60,5.0
3,6,0,15.400000,2179.000000,88.50,8.0
4,4,1,16.000000,2179.000000,140.00,7.0
...,...,...,...,...,...,...
15656,7,0,20.770000,1248.000000,88.80,7.0
15657,11,0,16.090000,1480.390521,103.20,5.0
15658,7,0,20.510000,998.000000,67.04,5.0
15659,2,0,18.600000,1197.000000,81.86,5.0
15660,2,1,20.280000,1462.000000,103.25,5.0

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test = train_test_split(
X,y,test_size=0.2,random_state=43)

In [48]:
import numpy as np
from sklearn.metrics import mean_absolute_error
y_pred = np.full_like(y_test, y_train.mean(), dtype=np.float64)
baseline_mae = mean_absolute_error(y_test, y_pred)
print("Baseline MAE:", baseline_mae)

Baseline MAE: 645858.9231574512